/*
@TargetNode='localhost'
@GeneratedBy=v-federicoar
@GenerationDate=06/23/2025 10:22:24
@GenerationHost=DESKTOP-HG9KK6L
*/

instance of nxPackage as $nxPackage1ref
{
SourceInfo = "C:\\repositories\\samples\\solutions\\azure-machine-configuration\\scripts\\linux-config.ps1::7::9::nxPackage";
 Name = "nginx";
 ModuleName = "nxtools";
 ResourceID = "[nxPackage]nginx";
 Ensure = "Present";
 ModuleVersion = "1.5.0";
 ConfigurationName = "NginxInstall";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="v-federicoar";

                        GenerationDate="06/23/2025 10:22:24";

                        GenerationHost="DESKTOP-HG9KK6L";

                        Name="NginxInstall";

                    };
