/*
@TargetNode='localhost'
@GeneratedBy=v-federicoar
@GenerationDate=05/27/2025 10:58:19
@GenerationHost=DESKTOP-HG9KK6L
*/

instance of DSC_TimeZone as $DSC_TimeZone1ref
{
TimeZone = "Eastern Standard Time";
 IsSingleInstance = "Yes";
 ModuleVersion = "10.0.0";
 SourceInfo = "C:\\repositories\\samples\\solutions\\azure-automation-state-configuration\\playPublic\\timeZoneConfig.ps1::7::5::TimeZone";
 ModuleName = "ComputerManagementDsc";
 ResourceID = "[TimeZone]TimeZoneConfig";
 ConfigurationName = "TimeZoneCustom";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="v-federicoar";

                        GenerationDate="05/27/2025 10:58:19";

                        GenerationHost="DESKTOP-HG9KK6L";

                        Name="TimeZoneCustom";

                    };
