/*
@TargetNode='localhost'
@GeneratedBy=v-federicoar
@GenerationDate=05/19/2025 14:38:01
@GenerationHost=DESKTOP-HG9KK6L
*/

instance of DSC_TimeZone as $DSC_TimeZone1ref
{
ModuleName = "ComputerManagementDsc";
 TimeZone = "Eastern Standard Time";
 ModuleVersion = "10.0.0";
 SourceInfo = "::6::5::TimeZone";
 ResourceID = "[TimeZone]TimeZoneConfig";
 IsSingleInstance = "Yes";
 ConfigurationName = "TimeZoneCustom";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="v-federicoar";

                        GenerationDate="05/19/2025 14:38:01";

                        GenerationHost="DESKTOP-HG9KK6L";

                        Name="TimeZoneCustom";

                    };
